- CONTRIBUTORS.md
Hey @dshrest, @AdamFreemer, @GeneralMeow, and @cubadomingo. Can you guys take a look at this doc? I think it'd be a really cool idea to list all the contributors to this project and the locations they represent.
Do any of you all have any problems being included in this list? If so, feel free to let me know before this gets merged in.
Also, if I've listed a wrong location for any of you all let me know as well. Thanks! I appreciate all your guys' help so far!
> Adding contributors doc

- package.json
- src/components/BsSpecialLabel.jsx
- src/utils/bsSpecialLabelHelper.js
- src/utils/bsSpecialLabelHelper.test.js
- yarn.lock
> Fix proper label colors

- package.json
- src/components/contributors-map/MapMarkerPopupInformation.jsx
- src/components/contributors-map/__tests__/MapMarkerPopupInformation.test.js
- src/utils/contributors.json
- yarn.lock
Adding ability to render Emojis! Woo!!
> Integrating EmojiOne and Emojifying the Contributors Map

- CONTRIBUTORS.md
- src/components/AppInfo.jsx
- src/utils/contributors.json
> Fixed Typo on Appinfo Page

- package.json
- src/server/routes.js
- src/server/routes.test.js
- yarn.lock
Merging this PR into the `express-server` branch
> Express server tests

- Procfile
- README.md
> Optimizing for heroku

- package.json
- src/components/AboutPage.jsx
> Prepping for 1.1.0 release

- src/components/NavigationBar.jsx
- src/styles/navigation-bar.css
References #61.
Splits Navbar into two sections (left and right).
> Updating navbar styling

- package.json
- src/actions/searchActionCreators.jsx
- src/components/AboutPage.jsx
- src/components/App.test.jsx
- src/components/NavigationBar.jsx
- src/components/NavigationBar.test.jsx
- src/components/NotFoundPage.jsx
- src/components/NotFoundPage.test.jsx
- src/components/SearchBar.jsx
- src/containers/SearchPage.jsx
- src/containers/SearchPage.test.jsx
- src/index.js
- src/reducers/index.jsx
- src/reducers/searchReducer.jsx
- src/routes.jsx
- yarn.lock
This PR adds the feature to change add a search query term to the url on search and to search for packages if a search term is included in the url. It includes specs, all of which are currently passing.
> URL search query term

- README.md
- package.json
- src/components/AboutPage.jsx
- src/containers/SearchPage.jsx
- src/containers/SearchPage.test.jsx
- yarn.lock
> Prepping for v1.2.0 release

- src/components/App.jsx
- src/styles/bootstrap-overrides.css
> Overridding bootstrap's Label styles

- src/components/ContributingInformationRow.jsx
- src/components/SearchResult.jsx
- src/utils/encodingHelper.js
Adding base64 to utf8 encoding support
> Emojifying the result description

- src/components/NavigationBar.jsx
- src/components/SearchBar.jsx
- src/components/SearchBar.test.js
- src/components/SearchForm.jsx
- src/components/SearchForm.test.js
- src/containers/SearchPage.jsx
- src/styles/navigation-bar.css
- src/styles/search-bar.css
- Refactor of SearchBar into SearchForm and SearchBar
- Adds help icon to search bar for query help
- Changes the focus color and styles of the search bar
- Adds opacity setting on hover for `Find me on Github` link
@cubadomingo can you take a look at this when you get a chance? Also, regarding your suggestion about the question icon needing a little bit of padding in mobile view, feel free to mess around with that if you'd like. It's not a huge deal to me right now if we don't get it figured out, but it'd be cool to have!
> Enhancing SearchBar. Adding SearchForm

- CONTRIBUTING.md
- docs/developer-guide/express-usage.md
- docs/developer-guide/setting-up-your-environment.md
- docs/developer-guide/yarn-start.md
> Enhancing Developer Guide

- CONTRIBUTORS.md
- public/index.html
- src/utils/contributors.json
> Fix typo in app page title

- CONTRIBUTING.md
- README.md
- SUMMARY.md
- book.json
- docs/README.md
- docs/common-problems.md
- docs/create-react-app-readme.md
- docs/react/components.md
- docs/react/props.md
- docs/react/the-basics.md
- docs/react/using-props.md
- Cleans up docs
- Configures docs for GitBook
> Enhancing docs. Configuring for Gitbook

- package.json
- src/components/SearchResultsBox.jsx
- src/components/SearchResultsBox.test.js
- src/containers/SearchPage.jsx
- src/containers/SearchPage.test.jsx
- yarn.lock
> adds a message to searchResultsBox component if no results were found

- package.json
- src/components/SearchResultsList.jsx
- yarn.lock
Basically @cubadomingo's regular additions from PR #84 with some minor updates to the transition durations and times.
> Cubadomingo animate results

- src/components/AboutPage.jsx
- src/components/ContributorsPage.jsx
- src/components/NotFoundPage.jsx
- src/containers/SearchPage.jsx
> Adding page titles to all page components

- public/index.html
> Changing bootstrap css CDN from latest to 3.3.7
